name: Build and Deploy to Docker Hub & VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: asisserver/embeddings:latest

    - name: Verify Pushed Image
      run: docker pull asisserver/embeddings:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} 
        script: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asisserver/embeddings:latest
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop embeddings || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm embeddings || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name embeddings -p 7078:7078 --restart always \
          -e SECRET_KEY=${{ secrets.SECRET_KEY }} asisserver/embeddings:latest